@Author: Suresh <br>
@Date: 06-10-2024<br>
@Last modified by: Suresh <br>
@Last modified Date: 06-10-2024<br> 
@Title: Proprecessing Techniques<br>

Importing Necessary Libraries

In [17]:
import  numpy as np
import pandas as pd

In [18]:
url = r"C:\Users\Suresh\Desktop\pythonBl\machine_learning\preprocessing\data_preprocessing (1).csv"
df = pd.read_csv(url)

    Handling Missing Values

In [19]:
##for our data set we can use mean value to fill the missing values

df['Age'].fillna(df['Age'].mean(),inplace= True)

df['Salary'].fillna(df['Salary'].mean(), inplace= True)

C:\Users\Suresh\AppData\Local\Temp\ipykernel_5512\1462376637.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace= True)
C:\Users\Suresh\AppData\Local\Temp\ipykernel_5512\1462376637.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For exa

In [20]:
df

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [21]:
## Changing the datatype of Age and Salary from float to int
# to make the data cleaner and memory efficient

df['Age'] = df['Age'].astype(int)
df['Salary'] = df['Salary'].astype(int)
df

Country  Age  Salary Purchased
0   France   44   72000        No
1    Spain   27   48000       Yes
2  Germany   30   54000        No
3    Spain   38   61000        No
4  Germany   40   63777       Yes
5   France   35   58000       Yes
6    Spain   38   52000        No
7   France   48   79000       Yes
8  Germany   50   83000        No
9   France   37   67000       Yes

    Handling Categorical Data

In [22]:
# using One-hot encoding for 'Country' and 'Purchased'
## we are using one-hot encoding because we have two categorical columns
## 'drop_first = True' ->  one of the category is dropped this is to avoid dummy variable trap

df_encoded = pd.get_dummies(df, columns=['Country', 'Purchased'], drop_first=True)
df_encoded.astype(int)

Age  Salary  Country_Germany  Country_Spain  Purchased_Yes
0   44   72000                0              0              0
1   27   48000                0              1              1
2   30   54000                1              0              0
3   38   61000                0              1              0
4   40   63777                1              0              1
5   35   58000                0              0              1
6   38   52000                0              1              0
7   48   79000                0              0              1
8   50   83000                1              0              0
9   37   67000                0              0              1

    Dividing the data to training and testing data 

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
df = df_encoded

In [25]:
## Seperating the features X and targets Y

X = df.drop('Purchased_Yes', axis = 1)
y = df['Purchased_Yes']


In [26]:
## Splitting the data 
X_train, X_test, y_train , y_test = train_test_split(X, y, test_size=0.2 , random_state= 42)
# X_train['Country_Germany'].astype(int)
# X_train['Country_Spain'].astype(int)
# X_test['Country_Germany'].astype(int)
# X_test['Country_Spain'].astype(int)
X_train.astype(int)
X_test.astype(int)
y_train.astype(int)
y_test.astype(int)



8    0
1    1
Name: Purchased_Yes, dtype: int32

In [27]:
print('X_train')
print(X_train)
print('X_test')
print(X_test)

X_train
   Age  Salary  Country_Germany  Country_Spain
5   35   58000            False          False
0   44   72000            False          False
7   48   79000            False          False
2   30   54000             True          False
9   37   67000            False          False
4   40   63777             True          False
3   38   61000            False           True
6   38   52000            False           True
X_test
   Age  Salary  Country_Germany  Country_Spain
8   50   83000             True          False
1   27   48000            False           True


In [28]:
print('y_train')
print(y_train)
print('y_test')
print(y_test)

y_train
5     True
0    False
7     True
2    False
9     True
4     True
3    False
6    False
Name: Purchased_Yes, dtype: bool
y_test
8    False
1     True
Name: Purchased_Yes, dtype: bool


        Feature Scaling

In [29]:
## Feature Scaling for the data
from sklearn.preprocessing import StandardScaler

In [30]:
# Applying the feature scaling 
scaler = StandardScaler()

# fitting the scaler on training data
X_train_scaled = scaler.fit_transform(X_train)

# transform the testing data
# here we are not fitting because to avoid the Data leakage
# so that we knoe weather our model is learning correctly or not

X_test_scaled = scaler.transform(X_test)

        Splitting the Data

In [31]:
## Printing scaled data

print(X_train_scaled)

[[-0.73279795 -0.62602675 -0.57735027 -0.57735027]
 [ 1.02591713  1.01305491 -0.57735027 -0.57735027]
 [ 1.80756828  1.83259575 -0.57735027 -0.57735027]
 [-1.70986189 -1.0943358   1.73205081 -0.57735027]
 [-0.34197238  0.4276686  -0.57735027 -0.57735027]
 [ 0.24426598  0.05032859  1.73205081 -0.57735027]
 [-0.14655959 -0.27479497 -0.57735027  1.73205081]
 [-0.14655959 -1.32849033 -0.57735027  1.73205081]]


In [32]:
print(X_test_scaled) 

[[ 2.19839386  2.3009048   1.73205081 -0.57735027]
 [-2.29610025 -1.79679937 -0.57735027  1.73205081]]
